title: Kyle News
email: send@kyle.news
description: >- # this means to ignore newlines until "baseurl:"
  I'm Kyle. A Web Developer / Hacker / Entrepreneur. I'm based just outside of Cambridge, UK. Welcome!
baseurl: ""
url: "https://kyle.news" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: the_actual_kyle
github_username: kylekirkby
# Build settings
defaults:
  - scope:
      type: posts
    values:
      layout: post
plugins:
  - jekyll-feed
  - jekyll-tidy
  - japr
  - jekyll_picture_tag
include: ["_pages"]
picture:
  source: "assets/images"
  output: "generated"
  markup: "picture"
blog:
  tags:
    url: /feed/tags/
    title_append: " posts"
    layout: tag.html
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    line_class: test
    code_class: test
permalink: /feed/:title/
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: true
jekyll_tidy:
  compress_html: true
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
