title: Kyle News
email: send@kyle.news
description: >- # this means to ignore newlines until "baseurl:"
  I'm Kyle. A Web Developer / Hacker / Entrepreneur. I'm based just outside of Cambridge, UK. Welcome!
baseurl: ""
url: "https://kyle.news" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Build settings
defaults:
  - scope:
      type: posts
    values:
      layout: post
plugins:
  - jekyll-feed
  - japr
  - jekyll_picture_tag
include: ["_pages"]
picture:
  source: "assets/images"
  output: "generated"
  markup: "picture"
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: /blog/:title/
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false
